### ISSUE TITLE
[BUG] Add Authentication Token Argument to `register_s3`

### ISSUE THREAD

**Issue by rbardaji** [sci-ndp/scidx-py#16]
## Description
The `register_s3` function needs an input argument for the authentication token.

## Expected Behavior
The `register_s3` function should accept an additional argument that allows passing the necessary authentication token to operate correctly.

## Actual Behavior
Currently, the `register_s3` function does not accept an argument for the authentication token.

**Comment by saleemalharir1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [scidx-py: Add Authentication Token Argument to register_s3 #16](https://trello.com/c/fIwhFuyM/37-scidx-py-add-authentication-token-argument-to-registers3-16)

**Comment by rbardaji** [comment]
Done.
