### ISSUE TITLE
[BUG] Add Authentication Token Argument to `register_kafka`

### ISSUE THREAD

**Issue by rbardaji** [sci-ndp/scidx-py#17]
## Description
The `register_kafka` function needs an input argument for the authentication token.

## Expected Behavior
The `register_kafka` function should accept an additional argument that allows passing the necessary authentication token to operate correctly.

## Actual Behavior
Currently, the `register_kafka` function does not accept an argument for the authentication token.

**Comment by saleemalharir1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [scidx-py: Add Authentication Token Argument to register_kafka #17](https://trello.com/c/OB3y9Ven/39-scidx-py-add-authentication-token-argument-to-registerkafka-17)
