### ISSUE TITLE
[Feature] Implement Function to Retrieve API Token

### ISSUE THREAD

**Issue by rbardaji** [sci-ndp/scidx-py#20]
## Description
We need to implement a functionality in the library to obtain the token from the Restplus API. This will be a critical feature for authentication and authorization when making API calls.

## Expected Behavior
The function should:
1. Send a POST request to the API's authentication endpoint.
2. Include necessary credentials (e.g., username, password) in the request body.
3. Receive and parse the response to extract the token.
4. Handle any errors or exceptions that may occur during the request.

## Possible Solution
- Define a function named `get_api_token` that takes the necessary parameters for authentication.
- Use the `requests` library to send the POST request.
- Parse the JSON response to retrieve the token.
- Return the token or raise an appropriate exception if the request fails.

## Additional Context
Here's an example of the expected usage:

```python
def get_api_token(username: str, password: str) -> str:
    # Implementation here
    pass

# Example usage
token = get_api_token('my_username', 'my_password')
```

**Comment by saleemalharir1** [comment]
done and merged
