### ISSUE TITLE
feat/add_url

### ISSUE THREAD

**Issue by saleemalharir1** [sci-ndp/scidx-py#8]
## Description
The function `register_url` needs to be implemented to add a URL resource in the sciDX system. This function should handle API requests with detailed logging and error handling.

## Steps to Reproduce
For feature requests, list the steps required to implement the new function:
1. Define the new function `register_url`.
2. Implement detailed logging and error handling for API requests.
3. Ensure the function correctly handles the creation of URL resources.
4. Test the function with various inputs to ensure correct behavior.

## Expected Behavior
The function should successfully create a URL resource in the sciDX system and handle any errors gracefully, providing detailed error messages when failures occur.

## Actual Behavior
Currently, the function is not implemented and needs to be created.

## Possible Solution
Follow the structure of the provided `register_url` code to implement the function. Ensure that the API requests are correctly formatted and that error handling is robust.

## Additional Context
Add detailed logging for API requests and responses. Ensure that the function can handle various input scenarios and provide meaningful error messages when something goes wrong.

**Comment by rbardaji** [comment]
Done
